backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        $this->layout = 'login';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->loginAdmin()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use yii\web\Response;
use common\models\EmailSender;
use common\models\User;
use common\models\Host;
use yii\helpers\ArrayHelper;
use common\models\Events;
use common\models\Feedback;
use common\models\TvShow;
use Authy\AuthyApi;
use yii\widgets\ActiveForm;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'save-image', 'profile-show', 'get-tv-show'],
                'rules' => [
                    [
                        'actions' => ['signup', 'profile-show', 'get-tv-show'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'save-image', 'profile-show', 'get-tv-show'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
            'eauth' => [
                // required to disable csrf validation on OpenID requests
                'class' => \nodge\eauth\openid\ControllerBehavior::className(),
                'only' => ['login'],
            ],
        ];
    }

    public function beforeAction($action) {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }
    
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * @return mixed
     */
    public function actionGetTvShow()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        
        $status = false;
        $data = ['Sport' => null, 'Film' => null, 'Show' => null];
        if ($value = Yii::$app->request->get('value')) {
            $sport = TvShow::find()->where(['like', 'name', $value])->andWhere(['category_id' => 1])->limit(4)->all();
            $film = TvShow::find()->where(['like', 'name', $value])->andWhere(['category_id' => 2])->limit(4)->all();
            $show = TvShow::find()->where(['like', 'name', $value])->andWhere(['category_id' => 3])->limit(4)->all();
            $status = true;
            if ($sport) {
                $data['Sport'] = ArrayHelper::map($sport, 'id', 'name');
            }
            if ($film) {
                $data['Film'] = $film ? ArrayHelper::map($film, 'id', 'name') : null;
            }
            if ($show) {
                $data['Show'] = $show ? ArrayHelper::map($show, 'id', 'name') : null;
            }
        }

        return ['status' => $status, 'data' => $data];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionPublicProfile($id)
    {
        $user = User::findOne($id);
        $location = Host::find()->where(['user_id' => $id]);

        if (Yii::$app->request->get('location_id')) {
            $location->andWhere([
                'id' => Yii::$app->request->get('location_id')
            ]);
        }

        $feedback = $user->getUserFeedback();

        return $this->render('profile-show', [
            'user' => $user,
            'feedbacks' => $feedback,
            'location' => $location->orderBy(['created_at' => SORT_DESC])->one()
        ]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLoginAjax() {
        $model = new LoginForm();
        
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return ActiveForm::validate($model);
        }
    }

    public function actionSignupAjax() {
        $model = new SignupForm();
        
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post()) && ($user = $model->signup())) {
            if (Yii::$app->user->login($user)) {
                $modelU = User::findOne($user->id);
                EmailSender::sendEmail($modelU->email, 'Registration', 'signup', ['model' => $modelU]);
                return $this->goBack();
            }
        } else {
            return ActiveForm::validate($model);
        }
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin() {
        $this->layout = 'modal';

        $serviceName = \Yii::$app->getRequest()->getQueryParam('service');
        if (isset($serviceName)) {
            /** @var $eauth \nodge\eauth\ServiceBase */
            $eauth = Yii::$app->get('eauth')->getIdentity($serviceName);
            $eauth->setRedirectUrl(Yii::$app->getUser()->getReturnUrl());
            $eauth->setCancelUrl(Yii::$app->getUrlManager()->createAbsoluteUrl('site/login'));

            try {
                if ($eauth->authenticate()) {

                    $identity = User::findByEAuth($eauth);
                    $profile = $eauth->getAttributes();
                    //var_dump($profile);exit;
                    if(!User::find()->where(['username' => $profile['name'], 'email' => (isset($profile['email']))?$profile['email']:$profile['id']])->exists()){
                        $model = new User();
                        $model->username = (isset($profile['name']))?$profile['name']:$profile['id'];
                        $model->password = \Yii::$app->security->generateRandomString(8);
                        $model->password_hash = \Yii::$app->security->generatePasswordHash($model->password);
                        $model->auth_key = \Yii::$app->security->generateRandomString(8);
                        $model->username = $profile['name'];
                        $model->email = (isset($profile['email']))?$profile['email']:$profile['id'];
                        $model->signup_type = $eauth->getServiceName();
                        $model->social_id = (isset($profile['id']))?$profile['id']:'';
                        if ($model->save()) {
                          if (Yii::$app->getUser()->login($model)) {
                            $eauth->redirect();
                          }
                        }
                    }else{
                        $model = User::find()->where(['social_id' => (isset($profile['id']))?$profile['id']:$profile['id'],'username' => $profile['name'], 'email' => (isset($profile['email']))?$profile['email']:$profile['id']])->one();
                        if (Yii::$app->getUser()->login($model)) {
                          $eauth->redirect();
                        }
                    }
                    //Yii::$app->getUser()->login($identity);

                    // special redirect with closing popup window
//                    $eauth->redirect();
                }else {
                    // close popup window and redirect to cancelUrl
                    $eauth->cancel();
                }
            }
            catch (\nodge\eauth\ErrorException $e) {
                // save error to show it later
                Yii::$app->getSession()->setFlash('error', 'EAuthException: '.$e->getMessage());

                // close popup window and redirect to cancelUrl
//              $eauth->cancel();
                $eauth->redirect($eauth->getCancelUrl());
            }
        }
        
        if (!Yii::$app->user->isGuest) {
            Yii::$app->session->setFlash('successDataLogin');
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            Yii::$app->session->setFlash('successDataLogin');
        }
        return $this->render('login', [
            'model' => $model,
        ]);
        
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $this->layout = 'modal';
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->user->login($user)) {
                    $modelU = User::findOne($user->id);
                    EmailSender::sendEmail($modelU->email, 'Registration', 'signup', ['model' => $modelU]);
                    Yii::$app->session->setFlash('successDataSignup');
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed

frontend/views/site/_footer.php
<?php
/* @var $this yii\web\View */
use frontend\widgets\WLang;

$this->title = 'Sofan Home';
?>
<section class="footer">
	<div class="container">
		<div class="row footer-b-t">
			<div class="col-12 col-md-4 select-block">
				  <div class="form-group">
				    <?= WLang::widget(); ?>
				  </div>
			</div>
			<div class="col-12 col-md-8">
				<div class="row">
					<div class="col-4 sofan">
						<h6> <?= Yii::t('footer', ' Sofan'); ?></h6>
						<a href="/page/how_it_work"><?= Yii::t('footer', 'Come Funziona'); ?></a>
						<a href="/page/who_we_are"><?= Yii::t('footer', 'Chi Siamo'); ?></a>
						<a href="/page/faq"> <?= Yii::t('footer', 'FAQ'); ?> </a>
						<a href="/page/contact"> <?= Yii::t('footer', ' Contattaci'); ?></a>
					</div>
					<div class="col-4 termini">
						<h6>  <?= Yii::t('footer', 'Termini e condizioni'); ?></h6>
						<a href="/page/term_1"> <?= Yii::t('footer', 'Termini e condizioni'); ?></a>
						<a href="/page/term_2"> <?= Yii::t('footer', 'Privacy e coockie'); ?></a>
					</div>
					<div class="col-4 diventa">
						<a href="/en/host"><h6><?= Yii::t('footer', 'Diventa Host'); ?></h6>
						</a>
					</div>
				</div>
			</div>
			<div class="col-12" style="border-bottom: 1px solid #95989A; padding-top:  45.9px"></div>
		</div>
		<div class="row button-footer">
			<div class="col-12 col-sm-6 footer-text-button">
		        <p>&copy; Eternity SRLS <?php //= date('Y') ?></p>
			</div>
			<div class="col-12 col-sm-6 icon-block" style="text-align: right;">
				<a href="#"><img src="/images/facebook-icon-footer.PNG" style="width: 15px;height: 20px"></a>
				<a href="#"><img src="/images/twiter-icon-footer.PNG" style="width: 17px;height: 17px">
				</a>
				<a href="#"><img src="/images/instagram-icon-footer.PNG" style="width: 20px;height: 20px"></a>
			</div>
		</div>
	</div>
</section>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */

/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="container">
    <div class="row no-margin site-error">
        <div class="col-12 offset-0 col-md-8 offset-md-2 text-center">
            <h1 class="h1-title-error">#404</h1>
            <div class="denger-alert">
                <?= nl2br(Html::encode($message)) ?>
            </div>
            <p class="p-error">
                The above error occurred while the Web server was processing your request.
            </p>
            <p class="p-error">
                Please contact us if you think this is a server error. Thank you.
            </p>
        </div>
    </div>
</div>

frontend/views/site/index.php
<?php
use kartik\widgets\ActiveForm,
    frontend\models\EventsSearch,
    kartik\widgets\Select2,
    common\models\TvShowCategories,
    yii\helpers\Html,
    kartik\date\DatePicker,
    yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'Sofan Home';
$eventsSearch = new EventsSearch();
$tvArray = TvShowCategories::getAllWithCategory();
?>
<section class="home-img-block">
</section>

<section class="home-content-menu">
    <div class="container">
        <div class="section-3-input">
            <div class="row">
                <div class="col-11" data-wow-duration="1s" data-wow-delay="0.1s">
                        <h4>
                            <?= Yii::t('home', 'Cerca il tuo Evento'); ?>
                        </h4>
                        <p>
                            <?= Yii::t('home', 'Guarda il tuo programma TV preferito a casa di altri appassionati come te!'); ?>
                        </p>
                </div>
            </div>
            <?php $form = ActiveForm::begin(['id' => 'events-search-form', 'action' => Url::to(['/events']), 'method' => 'get']); ?>

                <div class="row index-input-block" data-wow-duration="2s" data-wow-delay="0.1s" style="padding-top: 35.3px;padding-bottom: 67.8px;">
                    <div class="col-12 col-sm-12 col-lg-5 col-xl-5 search-block">
                        <?= $form->field($eventsSearch, 'tv_show_id')->hiddenInput()->label(false); ?>
                        <?= $form->field($eventsSearch, 'tv_show_name')->textInput(['placeholder' => 'Tutti Eventi'])->label(false); ?>
                        <div style="position:relative;" class="js-search-tv-block">
                            <ul class="js-search-tv-ul show-dropdown">
                            </ul>
                        </div>
                    </div>
                    
                    
                    <div class="col-12 col-lg-7 col-xl-7 input-block">
                        <div class="row input-block-sof">
                            <div class="col-12 col-sm-6 col-lg-4 col-xl-4  dove-block">
                                <?= $form->field($eventsSearch, 'cityName')->textInput(["placeholder" => 'Dove', 'class' => 'form-control input-sofan form-dove'])->label(false); ?>
                            </div>

                            <div class="col-12 col-sm-6 col-lg-4  col-xl-4 data-block">
                            <?= $form->field($eventsSearch, 'date_start')
                                ->widget(DatePicker::className(), [
                                    'removeButton' => false,
                                    'value' => date('Y-m-d'),
                                    'readonly' => true,
                                    'options' => ["placeholder" => 'Data', 'class' => 'input-sofan form-data'],
                                    'pluginOptions' => [
                                        'autoclose' => true,
                                        'class' => '2222222222',
                                        'format' => 'yyyy-mm-dd',
                                        'startDate'=> '0d',
                                    ]
                                ])->label(false); ?>
                            </div>
                            
                            <div class="col-12 col-sm-12 col-lg-4 col-xl-4 cedra-block">
                                <?= Html::submitButton('Cerca<img src="/images/up-button.png" style="width: 10px;height: 15px;box-sizing: initial;padding-left:12px;margin-top:-1px;">', 
                                ['class' => 'cersa btn-sofan']) ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php ActiveForm::end(); ?>
            
        </div>
    </div>
</section>
<section class="hai-una" style="background-color:#F6F8FA;">
	<div class="container">
        <div class="una-padding">
            <div class="row">
                <div class="col-12 col-sm-8 col-md-8 main-triangle">
                        <img src="/images/Rectangle.png" style="height: 362.45px;width:578.12px" class="animated icons">
                </div>
                <div class="col-12 col-sm-4 col-md-4 rigt-block-text">
                    <h5 class="wow animate fadeInRight" data-wow-duration="1s" data-wow-delay="0.1s">
                        <?= Yii::t('home', 'Hai una TV <br> e una location?'); ?>
                    </h5>
                    <p class="wow animate fadeInRight" data-wow-duration="1s" data-wow-delay="0.1s">
                        <?= Yii::t('home', 'Con Sofan guadagni e <br>trovi nuovi amici !'); ?>
                    </p>
                    <a href="<?= Url::to(['/profile/host']); ?>" class="btn btn-primary btn-sofan wow animate fadeInRight" data-wow-duration="2s" data-wow-delay="0.05s">
                        <?= Yii::t('home', 'Diventa Host'); ?>
                    </a>
                </div>
            </div>
        </div>
	</div>
</section>
<section class="rerche-sofan">
	<div class="container">
		<div class="row perche-block">
			<div class="col-12 features-section">
				<h2>
                    <?= Yii::t('home', 'Perché Sofan?'); ?>
                </h2>
			</div>
			<div class="col-12 col-sm-4 hosts wow animate fadeInRight" data-wow-duration="1s" data-wow-delay="0.1s">
				<img src="/images/piggy-bank.png" style="height: 106.67px; width: 82.3px"
				 class="animated icons">
				<h4>
                    <?= Yii::t('home', 'Hosts'); ?>
                </h4>
				<p>
                    <?= Yii::t('home', "Possono recuperare una parte del costo dell'abbonamento pay TV"); ?>
                </p>

			</div>
			<div class="col-12 col-sm-4 hosts wow animate fadeInRight" data-wow-duration="2s" data-wow-delay="0.2s">
				<img src="/images/trusting-in-someone.png" class="animated icons" 
				style="height: 106.67px; width: 82.3px">
				<h4>
                    <?= Yii::t('home', 'Guests'); ?>
                </h4>
				<p>
                    <?= Yii::t('home', 'Hanno la possibilità di trovare un luogo confortevole ed economico dove guardare i loro programmi televesivi preferiti.'); ?>
                </p>
			</div>
			<div class="col-12 col-sm-4 hosts wow animate fadeInRight" data-wow-duration="3s" data-wow-delay="0.3">
				<img src="/images/team.png" class="animated icons"
				style="height: 106.67px; width: 100.3px">
				<h4>
                    <?= Yii::t('home', 'Entrambi'); ?>
                </h4>
				<p><?= Yii::t('home', 'condividono le proprie paassioni in un ambiente giovane e internazionale'); ?>
                </p>
			</div>
		</div>
	</div>
</section>
<script>
    $(function(){
        $(document).click(function(){
            $('.js-search-tv-ul').hide();
        });

        $(document).on('click', '.js-search-tv-ul .js-tv-show', function(event){
            $('.js-search-tv-ul').hide()
            $('.js-search-tv-ul').html('');
            var id = $(this).data('id');
            var text = $(this).text();
            $('#eventssearch-tv_show_id').val(id);
            $('#eventssearch-tv_show_name').val(text);
            event.stopPropagation();
        });

        $(document).on('click', '.js-search-tv-ul .js-tv-show-category, #eventssearch-tv_show_name', function(e){
            e.stopPropagation();
        });

        $(document).on('keyup', '#eventssearch-tv_show_name', function(){
            $('#eventssearch-tv_show_id').val('')
            var search_val = $(this).val();
            if (search_val.length > 2) {
                $.ajax({
                    url: '<?= Url::to(['/site/get-tv-show']) ?>/',
                    method: 'get',
                    dataType: 'json',
                    data: {value:search_val},
                    success: function (response) {
                        if (response.status && response.data) {
                            $('.js-search-tv-ul').show();
                            $('.js-search-tv-ul').html('')
                            if (response.data.length != 0) {
                                var group = response.data;
                                $.each(group, function( index, value ) {
                                    console.log('index ', index);
                                    if(value){
                                        $('.js-search-tv-ul').append('<li class="js-tv-show-category category-name ' + index.toLowerCase() + '">' + index + '</li>')
                                        console.log(value)
                                        $.each(value, function( i, v ) {
                                            $('.js-search-tv-ul').append('<li class="js-tv-show show-item" data-id="'+i+'">' + v + '</li>')
                                        })
                                    }
                                    //$('.js-search-tv-ul').append('<li class="js-tv-show" data-id="'+index+'">' + value + '</li>')
                                });
                            } else {
                                $('.js-search-tv-ul').append('<li class="text-center">Not found</li>')
                            }
                        } else {
                            $('.js-search-tv-ul').hide()
                            $('.js-search-tv-ul').html('')
                        }
                    }
                });
            } else {
                $('.js-search-tv-ul').hide()
                $('.js-search-tv-ul').html('')
            }
        })
    })
</script>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\widgets\Pjax;
use kartik\checkbox\CheckboxX;

$this->title = 'Login';
?>

<?php Pjax::begin(['id' => 'pjax-signup' . $uid, 'enablePushState' => false]); ?>

    <?php if (Yii::$app->session->hasFlash('successDataLogin')) { ?>
        <script>
            if ($modal.signupModal) {
                $modal.signupModal.close();
            }
            if ($modal.loginModal) {
                $modal.loginModal.close();
            }
            parent.location.reload();
        </script>
    <?php } ?>

    <div class="js-site-login">
        <?= \nodge\eauth\Widget::widget(['action' => 'site/login']); ?>
        <div class="col-lg-12 form-control-login">
            <div class="signup-or-separator">
                <span class="h6 signup-or-separator--text">
                    <?= Yii::t('login', 'O'); ?></span>
                <hr>
            </div>
            <?php $form = ActiveForm::begin(['id' => 'login-form', 'options' => ['data-pjax' => 'pjax-login' . $uid]]); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true, 
                "placeholder" => 'Indirizzo Email', 'class' => 'form-control input-sofan'])->label(false) ?>

                <?= $form->field($model, 'password')->passwordInput([
                    "placeholder" => "Password",'class' => 'form-control input-sofan' ])->label(false)
                 ?>
                 <div style="display: inline-block;">
                <?= $form->field($model, 'rememberMe')->widget(CheckboxX::classname(), [
                    'pluginOptions'=>['threeState'=>false]
                ])->label(false); ?>
                    
                </div>
                <div style="display: inline-block;padding-left: 5px;">
                <label style="color: #999;">
                    <?= Yii::t('login', 'Remember me'); ?>
                </label>
                </div>
                <div class="text-login" style="color:#999;">
                    <?= Yii::t('login', ''); ?>    <?= Html::a('Password dimenticata? ', ['site/request-password-reset']) ?>
                </div>

                <div class="form-group" style="margin-top: 20px;">
                    <?= Html::submitButton('Accesso', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
            <hr>
            <div class="row">
            <div class="col-6 col-md-7 text-bottom"><?= Yii::t('login', 'Non hai un account?'); ?></div>
            <div class="col-6 col-md-5 button-sign-im-login-form">
                <?= Html::a(Yii::t('login', 'Registrati'), null, ['class' => 'btn btn-primary js-go-to-signup']) ?>
            </div>
        </div>
        </div>
    </div>
        
<?php Pjax::end();  ?>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="row no-margin site-error">
        <div class="col-12 offset-0 col-md-6 offset-md-3 text-center">
            <h1 class="h1-title-request"><?= Html::encode($this->title) ?></h1>

            <p class="p-error">Please fill out your email. A link to reset password will be sent there.</p>

            <div class="row">
                <div class="col-12 offset-0 col-md-10 offset-md-1">
                    <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                    <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                    </div>

                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>